// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pi4_PixieVault_DemiBruls.Database;

#nullable disable

namespace pi4_PixieVault_DemiBruls.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240918184426_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.CollectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CollectionItemPictureId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasMaxLength(255)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CollectionItemPictureId");

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.CollectionItemCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionItemId")
                        .HasColumnType("int");

                    b.Property<int>("CollectionItemPictureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectionItemId");

                    b.HasIndex("CollectionItemPictureId");

                    b.HasIndex("UserId");

                    b.ToTable("CollectionItemsCopies");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.CollectionItemCopyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionItemCopyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionItemCopyId");

                    b.ToTable("CollectionItemCopyValues");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.CollectionItemPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollectionItemPictures");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.CollectionItem", b =>
                {
                    b.HasOne("pi4_PixieVault_DemiBruls.Models.Brand", null)
                        .WithMany("CollectionItems")
                        .HasForeignKey("BrandId");

                    b.HasOne("pi4_PixieVault_DemiBruls.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pi4_PixieVault_DemiBruls.Models.CollectionItemPicture", "CollectionItemPicture")
                        .WithMany()
                        .HasForeignKey("CollectionItemPictureId");

                    b.Navigation("Category");

                    b.Navigation("CollectionItemPicture");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.CollectionItemCopy", b =>
                {
                    b.HasOne("pi4_PixieVault_DemiBruls.Models.CollectionItem", "CollectionItem")
                        .WithMany("CollectionItemCopies")
                        .HasForeignKey("CollectionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pi4_PixieVault_DemiBruls.Models.CollectionItemPicture", "CollectionItemPicture")
                        .WithMany()
                        .HasForeignKey("CollectionItemPictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pi4_PixieVault_DemiBruls.Models.User", "User")
                        .WithMany("CollectionItemCopies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionItem");

                    b.Navigation("CollectionItemPicture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.CollectionItemCopyValue", b =>
                {
                    b.HasOne("pi4_PixieVault_DemiBruls.Models.CollectionItemCopy", "CollectionItemCopy")
                        .WithMany("CollectionItemCopyValue")
                        .HasForeignKey("CollectionItemCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionItemCopy");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.Brand", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.CollectionItem", b =>
                {
                    b.Navigation("CollectionItemCopies");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.CollectionItemCopy", b =>
                {
                    b.Navigation("CollectionItemCopyValue");
                });

            modelBuilder.Entity("pi4_PixieVault_DemiBruls.Models.User", b =>
                {
                    b.Navigation("CollectionItemCopies");
                });
#pragma warning restore 612, 618
        }
    }
}
